### ISSUE TITLE
Not compatible with latest release of RbNaCl 3.4.0

### ISSUE THREAD

**Issue by grempe** [mwpastore/securer_randomer#1]
New release 3.4.0 is out and `securer_randomer` doesn't want to work with it if installed.

Suggest loosening gem spec dependency from:

```
spec.add_runtime_dependency 'rbnacl', '~> 3.3.0'
```

to

```
spec.add_runtime_dependency 'rbnacl', '~> 3.3'
```

This will allow minor upgrades, not just patch level.

Suggest patch level new release of this gem with that change.

Cheers

**Comment by mwpastore** [comment]
Ironically, it was my patch to RbNaCl that caused them to bump the version! Thanks for the bug report and the fix. It's in master and I'll release 0.1.6 in a bit here.

**Comment by mwpastore** [comment]
Ah, and your patch too, apparently. 😄 We are on the same wavelength! https://www.youtube.com/watch?v=QXl6q6Xapog

**Comment by grempe** [comment]
Yes, I noticed both of us on the change log too. Funny. :)
